### ISSUE TITLE
--mirror

### ISSUE THREAD

**Issue by epsilon-jpage** [countzero/backup_github_repositories#6]
You use the git clone option "--mirror" which does not clone the actual files.  It's pretty much only the .git directory in each repo.  Which _is_ nice because of the history but doesn't backup also imply the files?

Also, you're using the git clone command against the SSH option of the github URL but reference the Personal Auth Token in your "userSecret" option which doesn't work with that URL.  Your git clone URL in line 198 should be ...

git clone --quiet "https://github.com/${fullName}.git" "${directory}"

.. in my opinion, and works fine when I tested.

**Comment by countzero** [comment]
@epsilon-jpage 

Hi,

first of all, thank you for your feedback.

I am intentionally using the --mirror flag to create a bare Git repository. Since the goal of this script is primarily the backup of a Git repository we do not need the latest work space. The work space (your project files) can be fully derived from the history of a bare Git repository.

I added a FAQ section to the Readme with instructions on how to do that:

https://github.com/countzero/backup_github_repositories#how-do-i-work-with-a-bare-repository

Best regards
Finn
